\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{subcaption}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{multirow}
\usepackage{amssymb} % for math symbols
\usepackage{amsmath} % for aligning equations
%\usepackage{hyperref}
\usepackage{textcomp}
\usepackage{mdframed}
\usepackage{longtable}
\usepackage{blindtext, rotating}
\usepackage{natbib} %hyperref - attaches link to references
\bibliographystyle{..//refs/styles/nature1.bst}
%\usepackage[hyphens]{url}
\usepackage{caption}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1}
\parindent 0pt
\usepackage{lineno}
%\linenumbers

%cross referencing:
\usepackage{xr}
\usepackage{xr-hyper}
\externaldocument{microclimates}

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
]{siderules}

%% R Script
<<label=libraries, echo=FALSE, results="asis", message=FALSE, warning=FALSE>>=
  options(stringsAsFactors=FALSE)
library(dplyr)
library(tidyr)
library(ggplot2)
@

\begin{document}

\noindent \textbf{\Large{Supplemental materials: Variation across space, species and methods in models of spring phenology}}

\noindent Authors:\\
C. J. Chamberlain $^{1,2,3}$ \& E. M. Wolkovich $^{1,2,4}$
\vspace{2ex}\\
\emph{Author affiliations:}\\
$^{1}$Arnold Arboretum of Harvard University, 1300 Centre Street, Boston, Massachusetts, USA; \\
$^{2}$Organismic \& Evolutionary Biology, Harvard University, 26 Oxford Street, Cambridge, Massachusetts, USA; \\
$^{3}$The Nature Conservancy, Durham, NC 27701 USA;\\
$^{4}$Forest \& Conservation Sciences, Faculty of Forestry, University of British Columbia, 2424 Main Mall, Vancouver, BC V6T 1Z4;\\
\vspace{2ex}
$^*$Corresponding author: 248.953.0189; c.chamberlain@tnc.org; 0000-0001-5495-3219\\


\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\labelitemi}{$-$}
\setkeys{Gin}{width=0.8\textwidth}


<<echo=FALSE, warning==FALSE, message=FALSE>>=

library(xtable)


@
\section*{Methods S1: Using simulations to test Bayesian models in Rstan}
To test all models, we used data simulations but simulation data can only take us so far in model interpretation. We first needed to be certain our models were operating correctly. To test our model function, we built test data and manipulated the effects of the parameters to make sure the models were reporting this information accurately. As building such data can be critical to testing models and better understanding them we provide a Shiny App and GitHub repository for this purpose for the models presented here. 

\section*{Methods S2: Data analysis and model equations}
Using Bayesian hierarchical models, we estimated the effects of site (i.e., `forest' sites modeled as `0' versus `urban` sites modeled as a `1'), method (i.e., HOBO logger climate data modeled as `0' and weather station climate data modeled as `1') and the interaction between site and method effects as predictors with species modeled hierarchically as grouping factors:

\begin{align*}
y_i &= \alpha_{species[i]} + \beta_{site_{species[i]}}X_{site} + \beta_{method_{species[i]}}X_{method} + \beta_{sitexmethod_{species[i]}}X_{sitexmethod}\\
&+ \epsilon_i \tag{1}\\
\end{align*}
\begin{align*}
\epsilon_i & \sim N(0,\sigma_y) \\
\end{align*}

The $\alpha$ and each of the five $\beta$ coefficients are modeled at the species level, as follows:

\begin{align*}
\alpha_{species} & \sim N(\mu_{\alpha}, \sigma_{\alpha}) \\
\beta_{site_{species}} & \sim N(\mu_{site}, \sigma_{site}) \\
\beta_{method_{species}} & \sim N(\mu_{method}, \sigma_{method}) \\
\beta_{sitexmethod_{species}} & \sim N(\mu_{sitexmethod}, \sigma_{sitexmethod}) \\
\end{align*}

where $i$ represents each unique observation, $species$ is the species, $\alpha$ represents the intercept, $\beta$ terms represent slope estimates, and $y$ is the number of growing degree days. 


\bibliography{..//refs/micro}

\section*{Supplemental tables and figures}
\subsection*{Tables}

% %EMWFeb2022  -- Consider adding 'See main text methods and Fig. \ref{{fig:musims}} for more details.' to S1-S5 tables. 
<<label=urban, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/urban_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from urban simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable. See main text methods and Fig \\ref{fig:musims} for more details.", 
        label="tab:urban",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@

<<label=prov, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/provmethod_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from provenance latitude simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable. See main text methods and Fig \\ref{fig:musims} for more details.", 
        label="tab:prov",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@

<<label=micros, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/micros_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from microclimate simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable. See main text methods and Fig \\ref{fig:musims} for more details.", 
        label="tab:micros",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=noisyws, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/noisyws_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from noisy weather station simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable. See main text methods and Fig \\ref{fig:musims} for more details.", 
        label="tab:noisyws",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=noisyhobo, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/noisyhobo_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from noisy HOBO logger simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable. See main text methods and Fig \\ref{fig:musims} for more details.", 
        label="tab:noisyhobo",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=real, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/urbmethod.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from empirical urban versus rural model}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:real",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=provreal, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/provmethod.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from empirical provenance latitude model}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:provreal",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@

\clearpage
\subsection*{Figures}
\iffalse
{\begin{figure} [H]
  \begin{center}
  \includegraphics[width=12cm]{..//phylodata/microtree_hfandts.pdf}
  \caption{Phylogeny indicating species across the two sites}\label{fig:phylo}
  \end{center}
  \end{figure}}
\fi
  
\begin{figure}[H]
    \centering
    \includegraphics[height=8cm, width=12cm]{..//analyses/figures/gddratio_fstars.pdf}
\caption{Using simulated data, we show how GDD measurement accuracy changes along varying GDD thresholds using a base temperature of (a) 0$^{\circ}$C and a sigma of 0.1$^{\circ}$C, (b) 0$^{\circ}$C and a sigma of 0.5$^{\circ}$C, (c) 10$^{\circ}$C and a sigma of 0.1$^{\circ}$C and (d) 10$^{\circ}$C and a sigma of 0.5$^{\circ}$C. GDD accuracy is measured as the observed GDD divided by the expected GDD. }
\label{fig:forecasts}
\end{figure}
  
{\begin{figure} [H]
  \begin{center}
  \includegraphics[width=16cm]{..//analyses/figures/climate_methodiff.pdf}
  \caption{Here we show a breakdown of the mean temperature differences in data across the two sites between the two methods with darker lines representing weather station data and the lighter, more transparent lines of varying line types representing the HOBO loggers: a) a series of smoothing splines of mean temperature differences measured as HOBO logger minus weather station and b) actual mean temperature differences measured as HOBO logger minus weather station. }\label{fig:climdiffs}
  \end{center}
  \end{figure}}
  
  
\begin{figure}[H]
      \centering
      \includegraphics[height=7cm, width=11cm]{..//analyses/figures/muplot_prov_real.pdf}
      \label{fig:muplotprov}
\caption{ Empirical Data: Using real data to test provenance latitude, we show the effects of provenance latitude and climate data method (weather station versus HOBO logger) on GDDs until budburst. The intercept represents the HOBO logger data for the rural forested site. More positive values indicate more GDDs are required for budburst whereas more negative values suggest fewer GDDs are required. Dots and thin lines show means and 90\% uncertainty intervals and thicker lines show 50\% uncertainty intervals. See Table \ref{tab:provreal} for full model output.}
\label{fig:prov}
\end{figure}

\begin{figure}[H]
    \centering
    \includegraphics[width=12cm]{..//analyses/figures/functype.pdf}
\caption{ Empirical Data: Using real data, we show (a) the effects of site (urban versus rural) and climate data method (weather station versus HOBO logger) on GDDs until budburst between shrubs versus tree species used in the study. We also show model output for the same relationship in (b). The 1:1 (dashed) line helps visualize that shrubs generally require fewer GDDs until budburst than trees. }
\label{fig:funcs}
\end{figure}

\begin{figure}[H]
      \centering
      \includegraphics[width=8cm]{..//analyses/figures/prov_hist.pdf}
\caption{ Histogram of provenance latitude data at the urban arboretum site.}
\label{fig:provhist}
\end{figure}


  




\end{document}