\documentclass{article}
\usepackage{Sweave}
\usepackage{float}
\usepackage{subcaption}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{siunitx}
\usepackage{multirow}
\usepackage{amssymb} % for math symbols
\usepackage{amsmath} % for aligning equations
%\usepackage{hyperref}
\usepackage{textcomp}
\usepackage{mdframed}
\usepackage{longtable}
\usepackage{blindtext, rotating}
\usepackage{natbib}
\bibliographystyle{..//refs/styles/gcb.bst}
%\usepackage[hyphens]{url}
\usepackage{caption}
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
\topmargin -1.5cm        
\oddsidemargin -0.04cm   
\evensidemargin -0.04cm
\textwidth 16.59cm
\textheight 21.94cm 
%\pagestyle{empty} %comment if want page numbers
\parskip 7.2pt
\renewcommand{\baselinestretch}{1}
\parindent 0pt
\usepackage{lineno}
%\linenumbers

%cross referencing:
\usepackage{xr}

\newmdenv[
  topline=true,
  bottomline=true,
  skipabove=\topsep,
  skipbelow=\topsep
]{siderules}

%% R Script
<<label=libraries, echo=FALSE, results="asis", message=FALSE, warning=FALSE>>=
  options(stringsAsFactors=FALSE)
library(dplyr)
library(tidyr)
library(ggplot2)
@

\begin{document}

\noindent \textbf{\Large{Supplemental materials: Understanding growing degree days to predict spring phenology under climate change}}

\noindent Authors:\\
Catherine J. Chamberlain, ORCID: 0000-0001-5495-3219 $^{1,2}$ \& E. M. Wolkovich $^{1,2,3}$
\vspace{2ex}\\
\emph{Author affiliations:}\\
$^{1}$Arnold Arboretum of Harvard University, 1300 Centre Street, Boston, Massachusetts, USA 02131; \\
$^{2}$Organismic \& Evolutionary Biology, Harvard University, 26 Oxford Street, Cambridge, Massachusetts, USA 02138; \\
$^{3}$Forest \& Conservation Sciences, Faculty of Forestry, University of British Columbia, 2424 Main Mall, Vancouver, BC V6T 1Z4\\
\vspace{2ex}
$^*$Corresponding author: 248.953.0189; cchamberlain@g.harvard.edu\\
\vspace{2ex}
Article acceptance date: 13 April 2021

\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\labelitemi}{$-$}
\setkeys{Gin}{width=0.8\textwidth}


<<echo=FALSE, warning==FALSE, message=FALSE>>=

library(xtable)


@
\section*{Methods S1: Using simulations to test Bayesian models in Rstan}
To test all models, we used data simulations but simulation data can only take us so far in model interpretation. We first needed to be certain our models were operating correctly. To test our model function, we built test data and manipulated the effects of the parameters and sigmas around these parameters to make sure the models were reporting this information accurately. Building test data is easy and we encourage readers to use the Shiny App and GitHub repository to use as a building block. 

\section*{Methods S2: Data analysis and model equations}
Using Bayesian hierarchical models, we estimated the effects of site (i.e., `forest` sites modeled as `0` versus `urban` sites modeled as a `1`), method (i.e., hobo logger climate data modeled as `0` and weather station climate data modeled as `1`) and the interaction between site and method effects as predictors with species modeled hierarchically as grouping factors:

\begin{align*}
y_i &= \alpha_{species[i]} + \beta_{site_{species[i]}}X_{site} + \beta_{method_{species[i]}}X_{method} + \beta_{sitexmethod_{species[i]}}X_{sitexmethod}\\
&+ \epsilon_i \tag{1}\\
\end{align*}
\begin{align*}
\epsilon_i & \sim N(0,\sigma_y) \\
\end{align*}

The $\alpha$ and each of the five $\beta$ coefficients are modeled at the species level, as follows:

\begin{align*}
\alpha_{species} & \sim N(\mu_{\alpha}, \sigma_{\alpha}) \\
\beta_{site_{species}} & \sim N(\mu_{site}, \sigma_{site}) \\
\beta_{method_{species}} & \sim N(\mu_{method}, \sigma_{method}) \\
\beta_{sitexmethod_{species}} & \sim N(\mu_{sitexmethod}, \sigma_{sitexmethod}) \\
\end{align*}

where $i$ represents each unique observation, $species$ is the species, $\alpha$ represents the intercept, $\beta$ terms represent slope estimates, and $y$ is the number of growing degree days. 


\bibliography{..//refs/micro}

\section*{Supplemental tables and figures}

{\begin{figure} [H]
  \begin{center}
  \includegraphics[width=12cm]{..//analyses/figures/climate_hfandts.pdf}
  \caption{Smoothing spline of mean temperature with 90\% credible interval across the two sites.}\label{fig:clim}
  \end{center}
  \end{figure}}

{\begin{figure} [H]
  -\begin{center}
  -\includegraphics[width=12cm]{..//phylodata/microtree_hfandts.pdf}
  -\caption{Phylogeny indicating species across the two sites}\label{fig:phylo}
  -\end{center}
  -\end{figure}}

<<label=noisyws, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/noisyws_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from noisy weather station simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:noisyws",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=noisyhobo, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/noisyhobo_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from noisy hobo logger simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:noisyhobo",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=micros, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/micros_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from microclimate simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:micros",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=urban, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/urban_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from urban simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:urban",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@


<<label=real, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/urbmethod.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from real data}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:real",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@
  

<<label=urbmethod, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/urbmethod_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from an urban effect and noisy weather station simulations}.We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:urbmethod",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@
  
\begin{figure}[H]
    \begin{subfigure}{.5\linewidth}
	    %\rule{\linewidth}{\linewidth}
      \caption{}
      \centering
      \includegraphics[height=7cm, width=11cm]{..//analyses/figures/muplot_prov.pdf}
      \label{fig:muplotprov}
    \end{subfigure}
  \begin{subfigure}{.5\linewidth}
	    %\rule{\linewidth}{\linewidth}
	    \caption{}
      \centering
      \includegraphics[height=4cm, width=8cm]{..//analyses/figures/gdd_methods_prov.pdf}
    \label{fig:gddprov}
  \end{subfigure}
\caption{ Using simulated data to test provenance latitude, we show (a) the effects of provenance latitude and climate data method (weather station data as `1' or hobo logger data as `0') on simulated growing degree days (GDDs) until budburst. More positive values indicate more GDDs are required for budburst whereas more negative values suggest fewer GDDs are required. Dots and thin lines show means and 90\% uncertainty intervals and thicker lines show 50\% uncertainty intervals. See Table \\ref{tab:prov} for full model output. We also show (b) histograms of GDDs at the Arboretum and Harvard Forest using weather station data and hobo logger data. }
\label{fig:prov}
\end{figure}

<<label=prov, results="asis", echo=FALSE, warning=FALSE, message=FALSE, fig.pos="H", fig.width=7, fig.height=4, fig.align='center'>>=

zmodtable<-read.csv("..//analyses/output/supptables/provmethod_fake.csv", header=TRUE)
rownames(zmodtable)<-zmodtable$X
  zmodtable<-zmodtable[,-1]      
colnames(zmodtable) <- c('mean','25%', '75%', '2.5%', '97.5%' )

mod.table <- xtable(zmodtable, caption="\\textbf{Estimates from provenance latitude simulations}. We present posterior means, as well as 50\\% and 95\\% uncertainty intervals from models in which the predictors have been standardized so that they are comparable.", 
        label="tab:prov",align=c(
               "|p{0.11\\textwidth}|",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}",
               "p{0.06\\textwidth}|"))

print(mod.table, include.rownames=TRUE, hline.after = c(-1,0,9,10),caption.placement="top",size="\\footnotesize",sanitize.rownames.function=identity)

@

\end{document}